@echo off
echo Starting Zorn OAuth Handler Service...
cd /d "e:\Zorn Website 2.0\backend\oauth-handler"
echo Installing dependencies...
call npm install
echo Starting OAuth handler on port 3003...
call npm start